from __future__ import annotations

PHASES = ("pack", "rns_gemm", "crt_export", "end_to_end")
SKIP_JSON_NAMES = {
    "review_report.json",
    "scenario_manifest.json",
    "autotune.json",
    "autotune-cache.json",
    "evidence_database.json",
}
CSV_FIELDS = [
    "capture_path",
    "scenario_family",
    "scenario_name",
    "scenario_source_role",
    "scenario_evidence_role",
    "scenario_domain_family",
    "scenario_algebra_family",
    "scenario_workflow_name",
    "scenario_phase_label",
    "scenario_reuse_profile",
    "scenario_lowering_role",
    "scenario_output_domain_requirement",
    "scenario_large_shape_role",
    "scenario_promotion_scope",
    "scenario_grouping_role",
    "scenario_bridge_role",
    "scenario_modulus_role",
    "scenario_prime_or_composite",
    "scenario_metadata_json",
    "semantics",
    "backend",
    "selected_kernel",
    "target_id",
    "device_name",
    "m",
    "n",
    "k",
    "finite_modulus",
    "prefix",
    "selected_prefix",
    "exact_wide_limb_count",
    "pack_mode",
    "reuse_contract_enabled",
    "reuse_contract_operand_role",
    "reuse_contract_setup_scope",
    "export_variant",
    "reconstruction_variant",
    "modulus_set",
    "residue_count_policy",
    "tile_shape_variant",
    "grouped_dispatch_task_count",
    "grouped_dispatch_status",
    "adaptive_grouped_scheduler_requested",
    "adaptive_grouped_scheduler_status",
    "adaptive_grouped_scheduler_active_entries",
    "adaptive_grouped_scheduler_launch_ratio",
    "resident_lifetime_enabled",
    "resident_lifetime_output_domain",
    "workspace_arena_enabled",
    "workspace_arena_repeat_allocation_free",
    "streaming_overlap_requested",
    "streaming_overlap_status",
    "hip_graph_replay_requested",
    "hip_graph_replay_status",
    "release_gate",
    "release_gate_review_status",
    "verification_amortization_policy",
    "error_detection_policy",
    "error_detection_mode",
    "error_detection_false_negative_policy",
    "workload_proxy_family",
    "workload_proxy_label",
    "output_domain",
    "median_pack_us",
    "median_rns_gemm_us",
    "median_crt_export_us",
    "median_end_to_end_us",
    "bottleneck_class",
    "bottleneck_phase",
    "bottleneck_share",
    "roofline_target",
    "optimization_hint",
    "event_bottleneck_class",
    "event_bottleneck_share",
    "estimated_ops",
    "estimated_bytes",
    "arithmetic_intensity_ops_per_byte",
    "measured_gops",
    "pack_bandwidth_gbs",
    "export_bandwidth_gbs",
    "isa_evidence",
    "isa_report_count",
    "isa_report_paths",
    "isa_report_backends",
    "isa_report_targets",
    "isa_report_symbol_count",
    "isa_device_symbol_count",
    "isa_wmma_count",
    "isa_mfma_count",
    "isa_global_store_count",
    "isa_lds_mentions",
    "isa_wait_instructions",
    "isa_instruction_lines",
    "isa_vgpr_count",
    "isa_sgpr_count",
    "isa_lds_bytes",
    "isa_scratch_bytes",
    "isa_occupancy",
    "isa_rga_statuses",
    "promotable",
    "promotion_blockers",
]
ISA_COUNT_FIELDS = {
    "wmma": "isa_wmma_count",
    "mfma": "isa_mfma_count",
    "global_store": "isa_global_store_count",
    "lds_mentions": "isa_lds_mentions",
    "wait_instructions": "isa_wait_instructions",
    "instruction_lines": "isa_instruction_lines",
}
ISA_MAX_FIELDS = {
    "vgpr_count": "isa_vgpr_count",
    "sgpr_count": "isa_sgpr_count",
    "lds_bytes": "isa_lds_bytes",
    "scratch_bytes": "isa_scratch_bytes",
    "occupancy": "isa_occupancy",
}
BACKEND_ALIASES = {
    "direct-hip": "direct-hip",
    "hip-direct": "direct-hip",
    "hip": "direct-hip",
    "hipblaslt": "hipblaslt",
    "ck": "ck",
    "rocwmma": "rocwmma",
    "wmma": "rocwmma",
    "vector-alu": "vector-alu",
    "vector-alu-int64": "vector-alu",
    "hip-vector-alu-int64": "vector-alu",
    "hip-vector-alu-int64-baseline": "vector-alu",
    "wrap64": "wrap64",
    "wrap64-byte-limb": "wrap64",
}
OPTIMIZATION_HINTS = {
    "compute_throughput": "Inspect selected kernels, ISA, occupancy, and accelerator choice before pack/export work.",
    "pack_bandwidth": "Inspect pack layout, prepack reuse, fusion, and H2D staging before GEMM tuning.",
    "export_bandwidth": "Inspect CRT/export, status traffic, compact output, and lazy output-domain policy.",
    "launch_api_overhead": "Inspect batching, HIP Graph replay, reuse contracts, and plan/workspace caching.",
    "transfer_bandwidth": "Inspect H2D/D2H staging, output layout, and host/device residency policy.",
    "status_overhead": "Inspect status memset/D2H policy and cases where overflow/status is impossible.",
    "mixed_phase_balance": "Compare phase-specific A/B runs before specializing a single phase.",
    "unclassified": "Capture stronger timing/event metadata before choosing an optimization target.",
}


