set(_RNS8_CK_HINTS)
if(RNS8_HIP_ROOT)
  list(APPEND _RNS8_CK_HINTS "${RNS8_HIP_ROOT}")
endif()
if(DEFINED ENV{ROCM_PATH})
  list(APPEND _RNS8_CK_HINTS "$ENV{ROCM_PATH}")
endif()
if(DEFINED ENV{HIP_PATH})
  list(APPEND _RNS8_CK_HINTS "$ENV{HIP_PATH}")
endif()
if(DEFINED ENV{VCPKG_ROOT})
  list(APPEND _RNS8_CK_HINTS "$ENV{VCPKG_ROOT}/installed/${VCPKG_TARGET_TRIPLET}")
endif()
list(APPEND _RNS8_CK_HINTS "${CMAKE_CURRENT_SOURCE_DIR}/vcpkg_installed/${VCPKG_TARGET_TRIPLET}" "/opt/rocm")

find_path(
  RNS8_CK_INCLUDE_DIR
  NAMES ck/ck.hpp ck.hpp
  HINTS ${_RNS8_CK_HINTS}
  PATH_SUFFIXES include
)

set(RNS8_CK_CANDIDATE FALSE)
set(RNS8_CK_EVIDENCE "not discovered")
if(RNS8_CK_INCLUDE_DIR)
  set(RNS8_CK_CANDIDATE TRUE)
  set(RNS8_CK_EVIDENCE "header=${RNS8_CK_INCLUDE_DIR}")
endif()
set(RNS8_CK_BACKEND_READY FALSE)
set(RNS8_CK_BACKEND_ENABLEMENT "disabled")
set(RNS8CK_FOUND FALSE)
