set(_RNS8_HIPBLASLT_HINTS)

function(_rns8_hipblaslt_append_hint path)
  if(path)
    file(TO_CMAKE_PATH "${path}" _rns8_hipblaslt_hint)
    list(APPEND _RNS8_HIPBLASLT_HINTS "${_rns8_hipblaslt_hint}")
    set(_RNS8_HIPBLASLT_HINTS "${_RNS8_HIPBLASLT_HINTS}" PARENT_SCOPE)
  endif()
endfunction()

if(RNS8_HIP_ROOT)
  _rns8_hipblaslt_append_hint("${RNS8_HIP_ROOT}")
endif()
if(DEFINED ENV{ROCM_PATH})
  _rns8_hipblaslt_append_hint("$ENV{ROCM_PATH}")
endif()
if(DEFINED ENV{HIP_PATH})
  _rns8_hipblaslt_append_hint("$ENV{HIP_PATH}")
endif()
if(DEFINED ENV{VCPKG_ROOT})
  _rns8_hipblaslt_append_hint("$ENV{VCPKG_ROOT}/installed/${VCPKG_TARGET_TRIPLET}")
endif()
if(WIN32)
  list(APPEND _RNS8_HIPBLASLT_HINTS "C:/Program Files/AMD/ROCm/7.1" "C:/Program Files/AMD/ROCm/6.4")
endif()
list(APPEND _RNS8_HIPBLASLT_HINTS "${CMAKE_CURRENT_SOURCE_DIR}/vcpkg_installed/${VCPKG_TARGET_TRIPLET}" "/opt/rocm")

find_package(
  hipblaslt
  CONFIG
  QUIET
  HINTS ${_RNS8_HIPBLASLT_HINTS}
  PATH_SUFFIXES lib/cmake/hipblaslt
)

find_path(
  RNS8_HIPBLASLT_INCLUDE_DIR
  NAMES hipblaslt/hipblaslt.h hipblaslt.h
  HINTS ${_RNS8_HIPBLASLT_HINTS}
  PATH_SUFFIXES include
)

find_library(
  RNS8_HIPBLASLT_LIBRARY
  NAMES hipblaslt
  HINTS ${_RNS8_HIPBLASLT_HINTS}
  PATH_SUFFIXES lib lib64 bin
)

find_file(
  RNS8_HIPBLASLT_DLL_A
  NAMES libhipblaslt.dll.a
  HINTS ${_RNS8_HIPBLASLT_HINTS}
  PATH_SUFFIXES lib lib64
)

find_file(
  RNS8_HIPBLASLT_DLL
  NAMES libhipblaslt.dll hipblaslt.dll
  HINTS ${_RNS8_HIPBLASLT_HINTS}
  PATH_SUFFIXES bin
)

if(NOT RNS8_HIPBLASLT_LIBRARY AND RNS8_HIPBLASLT_DLL_A)
  set(RNS8_HIPBLASLT_LIBRARY "${RNS8_HIPBLASLT_DLL_A}")
endif()

set(RNS8_HIPBLASLT_TARGET "")
set(RNS8_HIPBLASLT_IMPORTED_IMPLIB "")
set(RNS8_HIPBLASLT_IMPORTED_LOCATION "")
if(TARGET roc::hipblaslt)
  set(RNS8_HIPBLASLT_TARGET "roc::hipblaslt")
  get_target_property(RNS8_HIPBLASLT_IMPORTED_IMPLIB roc::hipblaslt IMPORTED_IMPLIB_RELEASE)
  get_target_property(RNS8_HIPBLASLT_IMPORTED_LOCATION roc::hipblaslt IMPORTED_LOCATION_RELEASE)
  if(NOT RNS8_HIPBLASLT_IMPORTED_IMPLIB OR RNS8_HIPBLASLT_IMPORTED_IMPLIB STREQUAL "RNS8_HIPBLASLT_IMPORTED_IMPLIB-NOTFOUND")
    set(RNS8_HIPBLASLT_IMPORTED_IMPLIB "")
  endif()
  if(NOT RNS8_HIPBLASLT_IMPORTED_LOCATION OR RNS8_HIPBLASLT_IMPORTED_LOCATION STREQUAL "RNS8_HIPBLASLT_IMPORTED_LOCATION-NOTFOUND")
    set(RNS8_HIPBLASLT_IMPORTED_LOCATION "")
  endif()
  if(NOT RNS8_HIPBLASLT_INCLUDE_DIR)
    get_target_property(_RNS8_HIPBLASLT_TARGET_INCLUDES roc::hipblaslt INTERFACE_INCLUDE_DIRECTORIES)
    if(_RNS8_HIPBLASLT_TARGET_INCLUDES)
      list(GET _RNS8_HIPBLASLT_TARGET_INCLUDES 0 RNS8_HIPBLASLT_INCLUDE_DIR)
    endif()
  endif()
  if(NOT RNS8_HIPBLASLT_LIBRARY AND RNS8_HIPBLASLT_IMPORTED_IMPLIB)
    set(RNS8_HIPBLASLT_LIBRARY "${RNS8_HIPBLASLT_IMPORTED_IMPLIB}")
  endif()
  if(NOT RNS8_HIPBLASLT_DLL AND RNS8_HIPBLASLT_IMPORTED_LOCATION)
    set(RNS8_HIPBLASLT_DLL "${RNS8_HIPBLASLT_IMPORTED_LOCATION}")
  endif()
endif()

find_program(
  RNS8_HIPBLASLT_BENCH
  NAMES hipblaslt-bench hipblaslt-bench.exe
  HINTS ${_RNS8_HIPBLASLT_HINTS}
  PATH_SUFFIXES bin
)

set(RNS8_HIPBLASLT_CANDIDATE FALSE)
set(RNS8_HIPBLASLT_EVIDENCE "not discovered")
if(RNS8_HIPBLASLT_TARGET OR RNS8_HIPBLASLT_INCLUDE_DIR OR RNS8_HIPBLASLT_LIBRARY OR RNS8_HIPBLASLT_DLL OR RNS8_HIPBLASLT_BENCH)
  set(RNS8_HIPBLASLT_CANDIDATE TRUE)
  set(RNS8_HIPBLASLT_EVIDENCE)
  if(RNS8_HIPBLASLT_TARGET)
    list(APPEND RNS8_HIPBLASLT_EVIDENCE "target=${RNS8_HIPBLASLT_TARGET}")
  endif()
  if(RNS8_HIPBLASLT_INCLUDE_DIR)
    list(APPEND RNS8_HIPBLASLT_EVIDENCE "header=${RNS8_HIPBLASLT_INCLUDE_DIR}")
  endif()
  if(RNS8_HIPBLASLT_LIBRARY)
    list(APPEND RNS8_HIPBLASLT_EVIDENCE "library=${RNS8_HIPBLASLT_LIBRARY}")
  endif()
  if(RNS8_HIPBLASLT_IMPORTED_IMPLIB)
    list(APPEND RNS8_HIPBLASLT_EVIDENCE "imported_implib=${RNS8_HIPBLASLT_IMPORTED_IMPLIB}")
  endif()
  if(RNS8_HIPBLASLT_DLL)
    list(APPEND RNS8_HIPBLASLT_EVIDENCE "dll=${RNS8_HIPBLASLT_DLL}")
  endif()
  if(RNS8_HIPBLASLT_BENCH)
    list(APPEND RNS8_HIPBLASLT_EVIDENCE "tool=${RNS8_HIPBLASLT_BENCH}")
  endif()
endif()

set(RNS8_HIPBLASLT_MSVC_LINK_PROBE "not_run")
set(RNS8_HIPBLASLT_MSVC_LINK_PROBE_OUTPUT "")
if(RNS8_PROBE_ACCELERATORS AND MSVC AND TARGET roc::hipblaslt)
  set(_RNS8_HIPBLASLT_PROBE_SOURCE "${CMAKE_CURRENT_BINARY_DIR}/hipblaslt-msvc-link-probe.cpp")
  file(
    WRITE
    "${_RNS8_HIPBLASLT_PROBE_SOURCE}"
    "#include <hipblaslt/hipblaslt.h>\nint main() { hipblasLtHandle_t h = nullptr; return hipblasLtCreate(&h) == HIPBLAS_STATUS_SUCCESS && h ? (hipblasLtDestroy(h), 0) : 0; }\n"
  )
  try_compile(
    RNS8_HIPBLASLT_MSVC_LINK_PROBE_PASSED
    "${CMAKE_CURRENT_BINARY_DIR}/hipblaslt-msvc-link-probe"
    SOURCES "${_RNS8_HIPBLASLT_PROBE_SOURCE}"
    CXX_STANDARD 17
    COMPILE_DEFINITIONS "-D__HIP_PLATFORM_AMD__=1"
    LINK_LIBRARIES roc::hipblaslt
    OUTPUT_VARIABLE RNS8_HIPBLASLT_MSVC_LINK_PROBE_OUTPUT
  )
  if(RNS8_HIPBLASLT_MSVC_LINK_PROBE_PASSED)
    set(RNS8_HIPBLASLT_MSVC_LINK_PROBE "passed")
  elseif(RNS8_HIPBLASLT_MSVC_LINK_PROBE_OUTPUT MATCHES "Cannot open include file: '(memory|cstdint)'")
    set(RNS8_HIPBLASLT_MSVC_LINK_PROBE "not_run_missing_msvc_environment")
  else()
    set(RNS8_HIPBLASLT_MSVC_LINK_PROBE "failed")
  endif()
  string(REPLACE "\n" " | " RNS8_HIPBLASLT_MSVC_LINK_PROBE_OUTPUT "${RNS8_HIPBLASLT_MSVC_LINK_PROBE_OUTPUT}")
  string(REPLACE "\r" " " RNS8_HIPBLASLT_MSVC_LINK_PROBE_OUTPUT "${RNS8_HIPBLASLT_MSVC_LINK_PROBE_OUTPUT}")
  if(RNS8_HIPBLASLT_EVIDENCE)
    list(APPEND RNS8_HIPBLASLT_EVIDENCE "msvc_link_probe=${RNS8_HIPBLASLT_MSVC_LINK_PROBE}")
  endif()
endif()

set(RNS8_HIPBLASLT_BACKEND_READY FALSE)
set(RNS8_HIPBLASLT_BACKEND_ENABLEMENT "disabled")
set(RNS8HIPBLASLT_FOUND "${RNS8_HIPBLASLT_CANDIDATE}")
