include(FindPackageHandleStandardArgs)

set(_RNS8_ROCWMMA_HINTS)
if(RNS8_HIP_ROOT)
  list(APPEND _RNS8_ROCWMMA_HINTS "${RNS8_HIP_ROOT}")
endif()
if(DEFINED ENV{ROCM_PATH})
  list(APPEND _RNS8_ROCWMMA_HINTS "$ENV{ROCM_PATH}")
endif()
if(DEFINED ENV{HIP_PATH})
  list(APPEND _RNS8_ROCWMMA_HINTS "$ENV{HIP_PATH}")
endif()
if(DEFINED ENV{VCPKG_ROOT})
  list(APPEND _RNS8_ROCWMMA_HINTS "$ENV{VCPKG_ROOT}/installed/${VCPKG_TARGET_TRIPLET}")
endif()
list(APPEND _RNS8_ROCWMMA_HINTS "${CMAKE_CURRENT_SOURCE_DIR}/vcpkg_installed/${VCPKG_TARGET_TRIPLET}" "/opt/rocm")

find_path(
  RNS8_ROCWMMA_INCLUDE_DIR
  NAMES rocwmma/rocwmma.hpp
  HINTS ${_RNS8_ROCWMMA_HINTS}
  PATH_SUFFIXES include
)

find_package_handle_standard_args(RNS8ROCWMMA REQUIRED_VARS RNS8_ROCWMMA_INCLUDE_DIR)

set(RNS8_ROCWMMA_CANDIDATE FALSE)
if(RNS8_ROCWMMA_INCLUDE_DIR)
  set(RNS8_ROCWMMA_CANDIDATE TRUE)
endif()

if(RNS8ROCWMMA_FOUND)
  set(RNS8_ROCWMMA_INCLUDE_DIRS "${RNS8_ROCWMMA_INCLUDE_DIR}")
endif()
