set(_RNS8_HIPBLASLT_HINTS)
if(RNS8_HIP_ROOT)
  list(APPEND _RNS8_HIPBLASLT_HINTS "${RNS8_HIP_ROOT}")
endif()
if(DEFINED ENV{ROCM_PATH})
  list(APPEND _RNS8_HIPBLASLT_HINTS "$ENV{ROCM_PATH}")
endif()
if(DEFINED ENV{HIP_PATH})
  list(APPEND _RNS8_HIPBLASLT_HINTS "$ENV{HIP_PATH}")
endif()
if(DEFINED ENV{VCPKG_ROOT})
  list(APPEND _RNS8_HIPBLASLT_HINTS "$ENV{VCPKG_ROOT}/installed/${VCPKG_TARGET_TRIPLET}")
endif()
list(APPEND _RNS8_HIPBLASLT_HINTS "${CMAKE_CURRENT_SOURCE_DIR}/vcpkg_installed/${VCPKG_TARGET_TRIPLET}" "/opt/rocm")

find_path(
  RNS8_HIPBLASLT_INCLUDE_DIR
  NAMES hipblaslt/hipblaslt.h hipblaslt.h
  HINTS ${_RNS8_HIPBLASLT_HINTS}
  PATH_SUFFIXES include
)

find_library(
  RNS8_HIPBLASLT_LIBRARY
  NAMES hipblaslt
  HINTS ${_RNS8_HIPBLASLT_HINTS}
  PATH_SUFFIXES lib lib64 bin
)

find_program(
  RNS8_HIPBLASLT_BENCH
  NAMES hipblaslt-bench hipblaslt-bench.exe
  HINTS ${_RNS8_HIPBLASLT_HINTS}
  PATH_SUFFIXES bin
)

set(RNS8_HIPBLASLT_CANDIDATE FALSE)
set(RNS8_HIPBLASLT_EVIDENCE "not discovered")
if(RNS8_HIPBLASLT_INCLUDE_DIR OR RNS8_HIPBLASLT_LIBRARY OR RNS8_HIPBLASLT_BENCH)
  set(RNS8_HIPBLASLT_CANDIDATE TRUE)
  set(RNS8_HIPBLASLT_EVIDENCE)
  if(RNS8_HIPBLASLT_INCLUDE_DIR)
    list(APPEND RNS8_HIPBLASLT_EVIDENCE "header=${RNS8_HIPBLASLT_INCLUDE_DIR}")
  endif()
  if(RNS8_HIPBLASLT_LIBRARY)
    list(APPEND RNS8_HIPBLASLT_EVIDENCE "library=${RNS8_HIPBLASLT_LIBRARY}")
  endif()
  if(RNS8_HIPBLASLT_BENCH)
    list(APPEND RNS8_HIPBLASLT_EVIDENCE "tool=${RNS8_HIPBLASLT_BENCH}")
  endif()
endif()
set(RNS8_HIPBLASLT_BACKEND_READY FALSE)
set(RNS8_HIPBLASLT_BACKEND_ENABLEMENT "disabled")
set(RNS8HIPBLASLT_FOUND FALSE)
