include(FindPackageHandleStandardArgs)

set(_RNS8_HIPBLASLT_HINTS)
if(RNS8_HIP_ROOT)
  list(APPEND _RNS8_HIPBLASLT_HINTS "${RNS8_HIP_ROOT}")
endif()
if(DEFINED ENV{ROCM_PATH})
  list(APPEND _RNS8_HIPBLASLT_HINTS "$ENV{ROCM_PATH}")
endif()
if(DEFINED ENV{HIP_PATH})
  list(APPEND _RNS8_HIPBLASLT_HINTS "$ENV{HIP_PATH}")
endif()
if(DEFINED ENV{VCPKG_ROOT})
  list(APPEND _RNS8_HIPBLASLT_HINTS "$ENV{VCPKG_ROOT}/installed/${VCPKG_TARGET_TRIPLET}")
endif()
list(APPEND _RNS8_HIPBLASLT_HINTS "${CMAKE_CURRENT_SOURCE_DIR}/vcpkg_installed/${VCPKG_TARGET_TRIPLET}" "/opt/rocm")

find_path(
  RNS8_HIPBLASLT_INCLUDE_DIR
  NAMES hipblaslt/hipblaslt.h hipblaslt.h
  HINTS ${_RNS8_HIPBLASLT_HINTS}
  PATH_SUFFIXES include
)

find_library(
  RNS8_HIPBLASLT_LIBRARY
  NAMES hipblaslt
  HINTS ${_RNS8_HIPBLASLT_HINTS}
  PATH_SUFFIXES lib lib64 bin
)

find_program(
  RNS8_HIPBLASLT_BENCH
  NAMES hipblaslt-bench hipblaslt-bench.exe
  HINTS ${_RNS8_HIPBLASLT_HINTS}
  PATH_SUFFIXES bin
)

find_package_handle_standard_args(
  RNS8HIPBLASLT
  REQUIRED_VARS RNS8_HIPBLASLT_INCLUDE_DIR RNS8_HIPBLASLT_LIBRARY
)

set(RNS8_HIPBLASLT_CANDIDATE FALSE)
if(RNS8_HIPBLASLT_INCLUDE_DIR OR RNS8_HIPBLASLT_LIBRARY OR RNS8_HIPBLASLT_BENCH)
  set(RNS8_HIPBLASLT_CANDIDATE TRUE)
endif()

if(RNS8HIPBLASLT_FOUND)
  set(RNS8_HIPBLASLT_INCLUDE_DIRS "${RNS8_HIPBLASLT_INCLUDE_DIR}")
  set(RNS8_HIPBLASLT_LIBRARIES "${RNS8_HIPBLASLT_LIBRARY}")
endif()
