set(_RNS8_ROCWMMA_HINTS)
if(RNS8_HIP_ROOT)
  list(APPEND _RNS8_ROCWMMA_HINTS "${RNS8_HIP_ROOT}")
endif()
if(DEFINED ENV{ROCM_PATH})
  list(APPEND _RNS8_ROCWMMA_HINTS "$ENV{ROCM_PATH}")
endif()
if(DEFINED ENV{HIP_PATH})
  list(APPEND _RNS8_ROCWMMA_HINTS "$ENV{HIP_PATH}")
endif()
if(DEFINED ENV{VCPKG_ROOT})
  list(APPEND _RNS8_ROCWMMA_HINTS "$ENV{VCPKG_ROOT}/installed/${VCPKG_TARGET_TRIPLET}")
endif()
list(APPEND _RNS8_ROCWMMA_HINTS "${CMAKE_CURRENT_SOURCE_DIR}/vcpkg_installed/${VCPKG_TARGET_TRIPLET}" "/opt/rocm")

find_path(
  RNS8_ROCWMMA_INCLUDE_DIR
  NAMES rocwmma/rocwmma.hpp
  HINTS ${_RNS8_ROCWMMA_HINTS}
  PATH_SUFFIXES include
)

set(RNS8_ROCWMMA_CANDIDATE FALSE)
set(RNS8_ROCWMMA_EVIDENCE "not discovered")
if(RNS8_ROCWMMA_INCLUDE_DIR)
  set(RNS8_ROCWMMA_CANDIDATE TRUE)
  set(RNS8_ROCWMMA_EVIDENCE "header=${RNS8_ROCWMMA_INCLUDE_DIR}")
endif()
set(RNS8_ROCWMMA_BACKEND_READY FALSE)
set(RNS8_ROCWMMA_BACKEND_ENABLEMENT "disabled")
set(RNS8ROCWMMA_FOUND FALSE)
