#!/usr/bin/env python3
import argparse
from pathlib import Path

MODS = [256,255,253,251,247,239,233,229,227,223,217,211,199,197,193,191,181,179,173,167,163,157,151,149,139,137,131,127]

def gen(out):
    out.mkdir(parents=True, exist_ok=True)
    p = out / "rns8_generated_centered_reducers.cuh"
    with open(p, "w") as f:
        f.write("// Auto-generated by tools/generate_modulus_kernels.py. Do not edit.\n")
        f.write("#pragma once\n\n")
        for m in MODS:
            h = m // 2
            f.write(f"template<> __device__ __forceinline__ int8_t rns8_center_mod{m}_device(int32_t a){{int32_t r=a%{m};if(r<0)r+={m};return (int8_t)(r>{h}?r-{m}:r);}}\n")
    print(f"Generated {p}")

def main():
    a = argparse.ArgumentParser()
    a.add_argument("--out-dir", type=Path, default=Path("src/generated"))
    args = a.parse_args()
    gen(Path(__file__).resolve().parents[1] / args.out_dir)
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
