#!/usr/bin/env python3
"""Generate modulus-specialized HIP kernel headers.

For each modulus in the default RNS8 ladder, generates a specialized
centered-residue reducer as a constexpr device function. The generated
kernels eliminate runtime modulus lookups and division/modulo operations
by using compile-time-known modulus values.

Output goes to src/generated/. These are build artifacts, not source files.
"""

from __future__ import annotations

import argparse
from pathlib import Path

DEFAULT_MODULI = (
    256, 255, 253, 251, 247, 239, 233, 229,
    227, 223, 217, 211, 199, 197, 193, 191,
    181, 179, 173, 167, 163, 157, 151, 149,
    139, 137, 131, 127,
)

HEADER = """// Auto-generated by tools/generate_modulus_kernels.py. Do not edit.
// Modulus-specialized centered-residue reducers for the RNS8 default ladder.

#pragma once

"""


def centered_reducer(modulus: int) -> str:
    """Generate a constexpr device function for centered residue reduction."""
    half = modulus // 2
    return f"""// Modulus-{modulus} centered reducer (generated)
template <>
__device__ __forceinline__ int8_t rns8_center_mod{modulus}_device(int32_t acc) {{
  int32_t reduced = acc % {modulus};
  if (reduced < 0) reduced += {modulus};
  return static_cast<int8_t>(reduced > {half} ? reduced - {modulus} : reduced);
}}
"""


def garner_weight(modulus: int, prefix_product: int | None = None) -> str:
    """Generate Garner CRT weight constant for a modulus."""
    return f"// Garner weight for modulus {modulus}\\n"
__device__ constexpr uint64_t rns8_garner_weight_{modulus} = 0;  // Placeholder: compute from prefix product
"


def generate_kernel_header(out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)

    # Generate centered reducers
    reducer_path = out_dir / "rns8_generated_centered_reducers.cuh"
    with open(reducer_path, "w", encoding="utf-8") as f:
        f.write(HEADER)
        f.write("// Centered residue reduction for each default modulus

")
        for m in DEFAULT_MODULI:
            f.write(centered_reducer(m))
            f.write("
")

    # Generate dispatch table
    dispatch_path = out_dir / "rns8_generated_reducer_dispatch.cuh"
    with open(dispatch_path, "w", encoding="utf-8") as f:
        f.write(HEADER)
        f.write("// Compile-time modulus-to-reducer dispatch

")
        f.write("template <int Modulus>
")
        f.write("__device__ __forceinline__ int8_t rns8_center_fixed_device(int32_t acc) {
")
        for m in DEFAULT_MODULI:
            f.write(f'  if constexpr (Modulus == {m}) return rns8_center_mod{m}_device(acc);
')
        f.write("  return 0;
")
        f.write("}
")

    # Generate modulus-to-index lookup
    lookup_path = out_dir / "rns8_generated_modulus_index.cuh"
    with open(lookup_path, "w", encoding="utf-8") as f:
        f.write(HEADER)
        f.write("// Modulus-to-index compile-time lookup

")
        f.write("template <int Modulus>
")
        f.write("__device__ constexpr int rns8_modulus_index_device() {
")
        for i, m in enumerate(DEFAULT_MODULI):
            f.write(f"  if constexpr (Modulus == {m}) return {i};
")
        f.write("  return -1;
")
        f.write("}
")

    print(f"Generated {reducer_path}")
    print(f"Generated {dispatch_path}")
    print(f"Generated {lookup_path}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", type=Path, default=Path("src/generated"),
                        help="output directory for generated headers")
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    out_dir = repo_root / args.out_dir
    generate_kernel_header(out_dir)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
