# Generated by tools/metadata_registry.py. Do not edit by hand.
from __future__ import annotations

BENCHMARK_EXECUTION_MODES = {
    'auto_native_to_rns_bridge',
    'benchmark_grouped_dispatch_evidence',
    'benchmark_hip_graph_replay_evidence',
    'benchmark_host_api_batch',
    'benchmark_owned_vector_alu_gemv_n1_native_buffers',
    'benchmark_owned_vector_alu_gemv_small_n_native_buffers',
    'benchmark_owned_vector_alu_native_buffers',
    'benchmark_streaming_overlap_resident_b_pipeline',
    'direct_hip_skinny_gemv_n1_resident_rns',
    'direct_hip_skinny_gemv_small_n_resident_rns',
    'hip_graph_replay_bounded_pack_gemm_export',
    'hip_graph_replay_exact_wide_pack_gemm_export',
    'hip_graph_replay_finite_u8_pack_gemm_export',
    'hip_graph_replay_resident_rns_chain',
    'hip_graph_replay_wrap64_pack_gemm_export',
    'internal_wrap64_rocwmma_candidate',
    'persistent_resident_matrices',
    'public_oneshot_transient_native_inputs',
    'public_runtime_vector_alu_gemv_n1_native_buffers',
    'public_runtime_vector_alu_gemv_small_n_native_buffers',
    'public_runtime_vector_alu_native_buffers',
    'resident_sparse_a_explicit_4_to_2_contract_dense_b_rns',
    'residue_chain_final_host_export',
    'residue_chain_independent_final_host_export',
    'residue_channel_fusion_native_inputs',
    'residue_current_rns_chain',
    'transient_native_a_resident_b_reuse',
    'transient_native_b_resident_a_reuse',
    'transient_uniform_small_i8_a_resident_i8_b_reuse',
    'transient_uniform_small_i8_ab_inputs',
    'transient_uniform_small_i8_b_resident_i8_a_reuse',
    'vector_native_host_export_repack_direct_rns_chain',
    'vector_native_to_direct_rns_chain',
}
BOUND_SOURCES = {
    'input_scan',
    'static_profile',
}
BOUND_DISCOVERY_SOURCES = {
    'input_exact_tile_bounds',
    'input_row_column_abs_summary',
    'static_profile_contract',
}
BOUND_KINDS = {
    'global_max_abs',
    'global_max_unsigned',
    'input_range_and_k',
    'none',
    'per_tile_max_abs',
    'per_tile_max_unsigned',
}
PACK_MODES = {
    'per_repeat_repack',
    'prepacked_reuse',
    'prepacked_reuse_a',
    'prepacked_reuse_b',
}
NEXT_OP_HINTS = {
    'auto',
    'final-export',
    'native-gemm',
    'native-to-rns',
    'reuse-b',
    'rns-gemm',
}
FUSION_MODES = {
    'none',
    'residue_channel_width3_experimental_benchmark_only',
}
REUSE_OPERAND_ROLES = {
    'A',
    'A+B',
    'B',
    'none',
}
GRAPH_REPLAY_STATUSES = {
    'captured',
    'not_requested',
    'replayed',
    'unsupported_stream_capture_not_executed',
}
STREAMING_OVERLAP_STATUSES = {
    'executed',
    'metadata_only_unsupported_for_execution_path',
    'not_requested',
}
WORKLOAD_PROXY_FAMILIES = {
    'dense_exact_arithmetic_proxy',
    'fhe_lattice_proxy',
    'not_requested',
}
SELECTOR_REJECTION_REASONS = {
    'backend not compiled',
    'identity/runtime mismatch',
    'no exact entry',
    'per-tile unsupported',
    'probe failed',
    'slower than selected',
    'unsupported semantics',
    'unvalidated entry',
    'workspace mismatch',
}
PREPACK_REUSE_STRATEGIES = {
    'none',
    'persistent_matrix_residency',
    'rocwmma_reusable_b_cache',
}
CONTRACT_PREFIX_POLICIES = {
    'fixed_requested',
    'fixed_requested_residue_chain',
    'minimum_proven',
    'per_tile_minimum',
    'semantic_specific_no_rns_prefix',
}
BOUNDED_SEMANTICS = {
    'bounded_i64',
    'bounded_u64',
}
EXACT_WIDE_SEMANTICS = {
    'exact_wide_signed',
    'exact_wide_unsigned',
}
FINITE_U8_SEMANTICS = {
    'finite_field_u8',
    'finite_ring_u8',
}
RNS_PREFIX_SEMANTICS = {
    'bounded_i64',
    'bounded_u64',
    'exact_wide_signed',
    'exact_wide_unsigned',
}
NON_RNS_PREFIX_SEMANTICS = {
    'finite_field_u8',
    'finite_ring_u8',
    'wrap_u64_mod_2_64',
}
HIP_RESIDENT_BACKENDS = {
    'amdgpu-builtins',
    'ck',
    'hip-direct',
    'hip-vector-alu-int64',
    'hipblaslt',
    'rocwmma',
}
CURRENT_CORRECTNESS_BACKENDS = {
    'cpu-reference',
    'hip-direct',
    'wrap64-byte-limb',
}
BACKEND_REQUESTED_VALUES = {
    'amdgpu-builtins',
    'auto',
    'ck',
    'cpu-reference',
    'hip-direct',
    'hip-vector-alu-int64',
    'hipblaslt',
    'rocwmma',
    'rocwmma-wrap64-candidate',
    'wrap64-byte-limb',
}
BACKEND_SELECTED_VALUES = {
    'amdgpu-builtins',
    'ck',
    'cpu-reference',
    'hip-direct',
    'hip-vector-alu-int64',
    'hipblaslt',
    'rocwmma',
    'wrap64-byte-limb',
}
GROUPED_DISPATCH_STATUSES = {
    'executed',
    'metadata_only_unsupported_for_execution_path',
    'not_requested',
}
GROUPED_DISPATCH_EXECUTION_STRATEGIES = {
    'device_grouped_exact_wide_export_kernel_batched_d2h',
    'device_grouped_pack_and_exact_wide_export_kernels_batched_d2h',
    'device_grouped_pack_gemm_and_bounded_export_kernels_batched_d2h',
    'device_grouped_pack_gemm_and_exact_wide_export_kernels_batched_d2h',
    'device_grouped_pack_gemm_and_finite_export_kernel_batched_d2h',
    'device_grouped_pack_gemm_host_exports',
    'host_phase_loop_batched_exact_wide_export_d2h',
    'host_phase_loop_per_task_export',
    'not_requested',
}
GROUPED_DISPATCH_BATCHED_EXACT_WIDE_EXPORT_STRATEGIES = {
    'device_grouped_exact_wide_export_kernel_batched_d2h',
    'device_grouped_pack_and_exact_wide_export_kernels_batched_d2h',
    'device_grouped_pack_gemm_and_exact_wide_export_kernels_batched_d2h',
    'host_phase_loop_batched_exact_wide_export_d2h',
}
GROUPED_DISPATCH_BATCHED_BOUNDED_EXPORT_STRATEGIES = {
    'device_grouped_pack_gemm_and_bounded_export_kernels_batched_d2h',
}
GROUPED_DISPATCH_BATCHED_FINITE_EXPORT_STRATEGIES = {
    'device_grouped_pack_gemm_and_finite_export_kernel_batched_d2h',
}
GROUPED_TASK_DESCRIPTOR_LAYOUTS = {
    'not_requested',
    'same_contract_bucketed_resident_task_triplets_v1',
    'same_shape_resident_task_triplets_v1',
}
GROUPED_TASK_BUCKET_POLICIES = {
    'not_requested',
    'same_contract_shape_buckets',
    'single_same_shape_bucket',
}
GROUPED_TASK_SOURCE_VERSION_POLICIES = {
    'not_requested',
    'per_task_monotonic_source_version_repack',
}
GROUPED_TASK_WORKSPACE_POLICIES = {
    'not_requested',
    'one_workspace_per_task_shared_plan',
}
GROUPED_TASK_MATRIX_OWNERSHIP_POLICIES = {
    'benchmark_owns_all_task_triplets_until_capture_end',
    'not_requested',
}
GROUPED_TASK_DESCRIPTOR_REUSE_POLICIES = {
    'not_requested',
    'reuse_after_shape_workspace_source_validation',
}
GROUPED_TASK_STRIDE_POLICIES = {
    'matrix_ld_matches_logical_shape_host_output_ld_explicit',
    'not_requested',
}
GROUPED_TASK_OUTPUT_CURRENTNESS_POLICIES = {
    'device_residue_current_after_grouped_gemm_host_output_after_export',
    'not_requested',
}
GROUPED_TASK_LIFETIME_POLICIES = {
    'not_requested',
    'task_matrices_and_workspaces_destroyed_after_capture',
}
GROUPED_TASK_CHECKSUM_POLICIES = {
    'combined_per_task_checksum_u64',
    'not_requested',
}
GROUPED_TASK_STATUS_POLICIES = {
    'fail_fast_per_task_operation_status',
    'not_requested',
}
GROUPED_TASK_DEVICE_DESCRIPTOR_POLICIES = {
    'device_pointer_tables_and_compact_slabs',
    'host_resident_task_loop',
    'not_requested',
}
GROUPED_STRATEGY_DEVICE_DESCRIPTOR_POLICIES = {
    'device_grouped_exact_wide_export_kernel_batched_d2h': 'device_pointer_tables_and_compact_slabs',
    'device_grouped_pack_and_exact_wide_export_kernels_batched_d2h': 'device_pointer_tables_and_compact_slabs',
    'device_grouped_pack_gemm_and_bounded_export_kernels_batched_d2h': 'device_pointer_tables_and_compact_slabs',
    'device_grouped_pack_gemm_and_exact_wide_export_kernels_batched_d2h': 'device_pointer_tables_and_compact_slabs',
    'device_grouped_pack_gemm_and_finite_export_kernel_batched_d2h': 'device_pointer_tables_and_compact_slabs',
    'device_grouped_pack_gemm_host_exports': 'device_pointer_tables_and_compact_slabs',
    'host_phase_loop_batched_exact_wide_export_d2h': 'host_resident_task_loop',
    'host_phase_loop_per_task_export': 'host_resident_task_loop',
    'not_requested': 'not_requested',
}
OUTPUT_DESTINATION_LAYOUTS = {
    'contiguous_row_major',
    'padded_row_major',
}
STATUS_HANDLING = {
    'not_applicable',
    'required',
    'structurally_elided',
}
OUTPUT_CONTRACT_DOMAINS = {
    'exact_wide_limb_host',
    'finite_u8_host',
    'native_i64_u64_host',
    'rns_residue_current',
    'wrap64_u64_host',
}
DIRECT_HIP_EXPORT_STAGING_POLICIES = {
    'disabled_by_RNS8_HIP_PINNED_EXPORT_STAGING',
    'exact_wide_signed_forced_only_local_gfx1100_padded_staging_loses',
    'forced_for_large_outputs_by_RNS8_HIP_PINNED_EXPORT_STAGING',
    'large_padded_outputs_only_default',
    'not_applicable',
    'wrap64_forced_only_pending_padded_staging_evidence',
}
PACK_LAYOUTS = {
    'finite_u8_centered_residue',
    'matrix_engine_transient_pack_layout',
    'native_i64_row_major',
    'native_i8_row_major_residue_channel_width3',
    'native_i8_row_major_uniform_small',
    'native_u64_row_major',
    'resident_rns_residue_planes',
    'transient_backend_pack_layout',
    'wrap64_byte_limb_planes',
}
RESIDUE_GROUP_LAYOUTS = {
    'first_prefix9_moduli_contiguous_width3_groups',
    'one_modulus_per_residue_plane',
}
TARGET_NAMESPACES = {
    'cpu',
    'gfx1100',
    'gfx11xx',
    'gfx12xx',
    'gfx9xx_gfx94x',
    'unknown',
}
PLACEHOLDER_GPU_TARGET_IDS = {
    '',
    'cpu',
    'n/a',
    'none',
    'not_applicable',
    'null',
    'unknown',
}
TIMING_PHASES = {
    'crt_export',
    'end_to_end',
    'matrix_alloc',
    'pack',
    'planning',
    'rns_gemm',
    'scheduling',
}
DIRECT_HIP_CORE_EVENTS = {
    'crt_export',
    'crt_export_d2h',
    'crt_export_kernel',
    'crt_export_status_d2h',
    'crt_export_status_memset',
    'finite_pack_a_h2d',
    'finite_pack_a_kernel',
    'finite_pack_b_h2d',
    'finite_pack_b_kernel',
    'pack',
    'pack_a_h2d',
    'pack_a_kernel',
    'pack_b_h2d',
    'pack_b_kernel',
    'pack_h2d',
    'pack_kernel',
    'rns_gemm',
    'rns_gemm_kernel_group',
    'rns_gemv_n1_kernel_group',
    'rns_gemv_small_n_kernel_group',
}
GROUPED_DISPATCH_EVENTS = {
    'exact_wide_export_compact_to_host',
    'exact_wide_export_d2h',
    'exact_wide_export_kernel',
    'grouped_residue_pointer_table_h2d',
    'rns_gemm_kernel_group',
}
VECTOR_ALU_GPU_EVENT_LABELS = {
    'vector_alu_i64_gemv_n1_kernel',
    'vector_alu_i64_gemv_small_n_kernel',
    'vector_alu_i64_kernel',
    'vector_alu_output_d2h',
    'vector_alu_pack_a_h2d',
    'vector_alu_pack_b_h2d',
    'vector_alu_status_d2h',
    'vector_alu_status_memset',
    'vector_alu_u64_gemv_n1_kernel',
    'vector_alu_u64_gemv_small_n_kernel',
    'vector_alu_u64_kernel',
}
HIPBLASLT_GPU_EVENT_LABELS = {
    'hipblaslt_i32_to_residue_reduce',
    'hipblaslt_int8_i32_matmul',
    'hipblaslt_pack_transpose_centered',
}
ACCELERATOR_GPU_EVENT_LABELS = {
    'amdgpu_builtin_cdna3_mfma_i32_16x16x32_i8_finite_kernel',
    'amdgpu_builtin_cdna3_mfma_i32_16x16x32_i8_kernel',
    'amdgpu_builtin_cdna3_mfma_i32_32x32x16_i8_finite_kernel',
    'amdgpu_builtin_cdna3_mfma_i32_32x32x16_i8_kernel',
    'amdgpu_builtin_cdna3_smfmac_i32_16x16x64_i8_sparse_a_finite_kernel',
    'amdgpu_builtin_cdna3_smfmac_i32_16x16x64_i8_sparse_a_kernel',
    'amdgpu_builtin_rdna3_wmma_i32_16x16x16_iu8_finite_kernel',
    'amdgpu_builtin_rdna3_wmma_i32_16x16x16_iu8_kernel',
    'amdgpu_builtin_rdna4_swmmac_i32_16x16x32_iu8_sparse_a_finite_kernel',
    'amdgpu_builtin_rdna4_swmmac_i32_16x16x32_iu8_sparse_a_kernel',
    'amdgpu_builtin_rdna4_wmma_i32_16x16x16_iu8_finite_kernel',
    'amdgpu_builtin_rdna4_wmma_i32_16x16x16_iu8_kernel',
    'ck_int8_matmul_kernel',
    'rocwmma_matmul_kernel',
    'rocwmma_matmul_prepacked_b_kernel',
    'rocwmma_pack_a_kernel',
    'rocwmma_pack_a_prepacked_b_kernel',
    'rocwmma_pack_b_kernel',
    'rocwmma_zero_output_tile_memset',
    'sparse_a_indices_h2d',
    'sparse_a_values_h2d',
}
GPU_EVENT_SOURCE_SCOPES = {
    'accelerator_backend_default_stream_deep_kernel_events_with_direct_hip_pack_export',
    'accelerator_backend_default_stream_operation_groups_with_direct_hip_pack_export',
    'direct_hip_bounded_adaptive_default_stream_backend_operation_groups',
    'direct_hip_default_stream_backend_operation_groups',
    'direct_hip_native_to_rns_bridge_default_stream_operation_groups',
    'direct_hip_oneshot_default_stream_operation_groups',
    'direct_hip_oneshot_resident_fallback_default_stream_operation_groups',
    'direct_hip_streaming_overlap_multistream_operation_groups',
    'direct_hip_vector_native_host_repack_chain_default_stream_operation_groups',
    'direct_hip_vector_native_to_rns_chain_default_stream_operation_groups',
    'direct_hip_wrap64_byte_gemm36_default_stream_backend_operation_groups',
    'hipblaslt_baseline_default_stream_backend_operation_groups',
    'rocwmma_wrap64_byte_gemm36_candidate_default_stream_operation_groups',
    'vector_alu_default_stream_native_int64_operation_groups',
}
DIRECT_HIP_GPU_EVENT_SCOPES = {
    'direct_hip_bounded_adaptive_default_stream_backend_operation_groups',
    'direct_hip_default_stream_backend_operation_groups',
    'direct_hip_native_to_rns_bridge_default_stream_operation_groups',
    'direct_hip_oneshot_default_stream_operation_groups',
    'direct_hip_oneshot_resident_fallback_default_stream_operation_groups',
    'direct_hip_streaming_overlap_multistream_operation_groups',
    'direct_hip_vector_native_host_repack_chain_default_stream_operation_groups',
    'direct_hip_vector_native_to_rns_chain_default_stream_operation_groups',
    'direct_hip_wrap64_byte_gemm36_default_stream_backend_operation_groups',
}
HIPBLASLT_GPU_EVENT_SCOPES = {
    'hipblaslt_baseline_default_stream_backend_operation_groups',
}
ACCELERATOR_GPU_EVENT_SCOPES = {
    'accelerator_backend_default_stream_deep_kernel_events_with_direct_hip_pack_export',
    'accelerator_backend_default_stream_operation_groups_with_direct_hip_pack_export',
    'rocwmma_wrap64_byte_gemm36_candidate_default_stream_operation_groups',
}
VECTOR_ALU_GPU_EVENT_SCOPES = {
    'vector_alu_default_stream_native_int64_operation_groups',
}
CK_DEEP_GPU_EVENT_LABELS = {
    'ck_add_centered_kernel',
    'ck_copy_centered_kernel',
    'ck_pack_a_kernel',
    'ck_pack_b_kernel',
    'ck_wmma_cshuffle_matmul',
    'ck_zero_output_tile_memset',
}
ROCWMMA_DEEP_GPU_EVENT_LABELS = {
    'rocwmma_matmul_kernel',
    'rocwmma_matmul_prepacked_b_kernel',
    'rocwmma_pack_a_kernel',
    'rocwmma_pack_a_prepacked_b_kernel',
    'rocwmma_pack_b_kernel',
    'rocwmma_zero_output_tile_memset',
}
AMDGPU_BUILTIN_DEEP_GPU_EVENT_LABELS = {
    'amdgpu_builtin_cdna3_mfma_i32_16x16x32_i8_finite_kernel',
    'amdgpu_builtin_cdna3_mfma_i32_16x16x32_i8_kernel',
    'amdgpu_builtin_cdna3_mfma_i32_32x32x16_i8_finite_kernel',
    'amdgpu_builtin_cdna3_mfma_i32_32x32x16_i8_kernel',
    'amdgpu_builtin_cdna3_smfmac_i32_16x16x64_i8_sparse_a_finite_kernel',
    'amdgpu_builtin_cdna3_smfmac_i32_16x16x64_i8_sparse_a_kernel',
    'amdgpu_builtin_rdna3_wmma_i32_16x16x16_iu8_finite_kernel',
    'amdgpu_builtin_rdna3_wmma_i32_16x16x16_iu8_kernel',
    'amdgpu_builtin_rdna4_swmmac_i32_16x16x32_iu8_sparse_a_finite_kernel',
    'amdgpu_builtin_rdna4_swmmac_i32_16x16x32_iu8_sparse_a_kernel',
    'amdgpu_builtin_rdna4_wmma_i32_16x16x16_iu8_finite_kernel',
    'amdgpu_builtin_rdna4_wmma_i32_16x16x16_iu8_kernel',
}
EPILOGUE_TYPES = {
    'canonical_u8_export',
    'crt_export',
    'low64_wrap_export',
    'residue_current_rns_output',
}
BACKEND_EPILOGUE_MODES = {
    'amdgpu_builtin_fused_i32_to_centered_residue_rns_output',
    'amdgpu_builtin_fused_i32_to_centered_residue_then_canonical_u8_export',
    'amdgpu_builtin_fused_i32_to_centered_residue_then_chained_crt_export',
    'ck_fused_i32_to_centered_residue_rns_output',
    'ck_fused_i32_to_centered_residue_then_canonical_u8_export',
    'ck_fused_i32_to_centered_residue_then_crt_export',
    'direct_int64_export',
    'fused_centered_residue_then_crt_export',
    'low64_wrap_export',
    'native_i64_u64_export',
    'native_input_centered_residue_rns_output',
    'native_input_centered_residue_then_crt_export',
    'rocwmma_fused_i32_to_centered_residue_rns_output',
    'rocwmma_fused_i32_to_centered_residue_then_canonical_u8_export',
    'rocwmma_fused_i32_to_centered_residue_then_crt_export',
    'separate_i32_scratch_reduce_rns_output',
    'separate_i32_scratch_reduce_then_canonical_u8_export',
    'separate_i32_scratch_reduce_then_crt_export',
}
GENERATED_REDUCER_IDENTITIES = {
    'direct_hip_finite_modulus_251_fixed_reducer_v1',
    'direct_hip_finite_modulus_255_fixed_reducer_v1',
    'direct_hip_finite_modulus_256_fixed_reducer_v1',
    'direct_hip_fixed_prefix_18_generated_reducer_v1',
    'direct_hip_fixed_prefix_1_generated_reducer_v1',
    'direct_hip_fixed_prefix_20_generated_reducer_v1',
    'direct_hip_fixed_prefix_2_generated_reducer_v1',
    'direct_hip_fixed_prefix_3_generated_reducer_v1',
    'direct_hip_fixed_prefix_4_generated_reducer_v1',
    'direct_hip_fixed_prefix_5_generated_reducer_v1',
    'direct_hip_fixed_prefix_6_generated_reducer_v1',
    'direct_hip_fixed_prefix_7_generated_reducer_v1',
    'direct_hip_fixed_prefix_8_generated_reducer_v1',
    'direct_hip_fixed_prefix_9_generated_reducer_v1',
    'not_applicable',
}
GENERATED_REDUCER_IDENTITY_PATTERNS = {
    'direct_hip_finite_modulus_[0-9]+_fixed_reducer_v1',
}
REDUCER_FAMILIES = {
    'finite_u8_centered_canonical_export',
    'rns_prefix_centered_crt_export',
}
SELECTED_KERNELS = {
    'amdgpu_builtin_cdna3_mfma_i32_16x16x32_i8_centered_epilogue_v1',
    'amdgpu_builtin_cdna3_mfma_i32_16x16x32_i8_finite_u8_epilogue_v1',
    'amdgpu_builtin_cdna3_mfma_i32_32x32x16_i8_centered_epilogue_v1',
    'amdgpu_builtin_cdna3_mfma_i32_32x32x16_i8_finite_u8_epilogue_v1',
    'amdgpu_builtin_cdna3_smfmac_i32_16x16x64_i8_sparse_a_v1',
    'amdgpu_builtin_rdna3_wmma_i32_16x16x16_iu4_research_v1',
    'amdgpu_builtin_rdna3_wmma_i32_16x16x16_iu8_centered_epilogue_v1',
    'amdgpu_builtin_rdna3_wmma_i32_16x16x16_iu8_finite_u8_epilogue_v1',
    'amdgpu_builtin_rdna4_swmmac_i32_16x16x32_iu4_sparse_a_research_v1',
    'amdgpu_builtin_rdna4_swmmac_i32_16x16x32_iu8_sparse_a_v1',
    'amdgpu_builtin_rdna4_wmma_i32_16x16x16_iu8_centered_epilogue_v1',
    'amdgpu_builtin_rdna4_wmma_i32_16x16x16_iu8_finite_u8_epilogue_v1',
    'ck_wmma_cshuffle_finite_u8_mod251_centered_epilogue_v2',
    'ck_wmma_cshuffle_finite_u8_mod255_centered_epilogue_v2',
    'ck_wmma_cshuffle_finite_u8_mod256_centered_epilogue_v2',
    'ck_wmma_cshuffle_finite_u8_static_modulus_centered_epilogue_v2',
    'ck_wmma_cshuffle_i8_i32_default_moduli_static_centered_epilogue_v3',
    'ck_wmma_cshuffle_tiled_i8_i32_default_moduli_static_centered_epilogue_v3',
    'cpu_reference',
    'direct_hip_grouped_active_prefix_schedule_rns_gemm_v3',
    'direct_hip_native_a_finite_u8_gemm_mod251_v1',
    'direct_hip_native_a_finite_u8_gemm_mod255_v1',
    'direct_hip_native_a_finite_u8_gemm_mod256_v1',
    'direct_hip_native_a_finite_u8_gemm_v1',
    'direct_hip_native_a_i64_prefix9_reuse_b_grouped_rns_gemm_v1',
    'direct_hip_native_a_u64_colpair_prefix9_reuse_b_grouped_rns_gemm_v2',
    'direct_hip_native_a_u64_prefix9_reuse_b_grouped_rns_gemm_v1',
    'direct_hip_native_b_u64_colpair_prefix9_reuse_a_grouped_rns_gemm_v1',
    'direct_hip_native_finite_u8_gemm_mod251_v1',
    'direct_hip_native_finite_u8_gemm_mod255_v1',
    'direct_hip_native_finite_u8_gemm_mod256_v1',
    'direct_hip_native_finite_u8_gemm_v1',
    'direct_hip_prefix20_grouped_rns_gemm_v1',
    'direct_hip_prefix9_grouped_rns_gemm_v1',
    'direct_hip_prefix9_native_input_colpair_grouped_rns_gemm_v2',
    'direct_hip_prefix9_native_input_grouped_rns_gemm_v1',
    'direct_hip_prefix9_rns_gemv_n1_i64_v1',
    'direct_hip_prefix9_rns_gemv_n1_u64_v1',
    'direct_hip_prefix9_rns_gemv_small_n_i64_v1',
    'direct_hip_prefix9_rns_gemv_small_n_u64_v1',
    'direct_hip_tiled_active_prefix_rns_gemm_v2',
    'direct_hip_tiled_active_prefix_zero_row_col_skip_rns_gemm_v1',
    'direct_hip_tiled_active_prefix_zero_skip_rns_gemm_v3',
    'direct_hip_tiled_active_prefix_zero_tile_row_col_skip_rns_gemm_v1',
    'direct_hip_tiled_finite_u8_gemm_mod251_v1',
    'direct_hip_tiled_finite_u8_gemm_mod255_v1',
    'direct_hip_tiled_finite_u8_gemm_mod256_v1',
    'direct_hip_tiled_finite_u8_gemm_v1',
    'direct_hip_tiled_rns_gemm_v1',
    'direct_hip_uniform_small_i8_ab_colpair_prefix9_residue_channel_width3_experimental_v0',
    'direct_hip_uniform_small_i8_ab_colpair_prefix9_reuse_a_grouped_rns_gemm_v1',
    'direct_hip_uniform_small_i8_ab_colpair_prefix9_reuse_b_grouped_rns_gemm_v2',
    'direct_hip_uniform_small_i8_ab_colpair_prefix9_transient_grouped_rns_gemm_v1',
    'direct_hip_wrap64_byte_gemm36_u32acc_colpair_2d_v5',
    'direct_hip_wrap64_byte_gemm36_u32acc_tiled_2d_v4',
    'direct_hip_wrap64_byte_gemm36_u64acc_tiled_2d_v4',
    'hip_vector_alu_i64_exact_192b_v1',
    'hip_vector_alu_i64_gemv_n1_exact_192b_v1',
    'hip_vector_alu_i64_gemv_small_n_exact_192b_v1',
    'hip_vector_alu_u64_exact_192b_v1',
    'hip_vector_alu_u64_gemv_n1_exact_192b_v1',
    'hip_vector_alu_u64_gemv_small_n_exact_192b_v1',
    'hipblaslt_int8_i32_scratch_reduce_specialized_251_255_256_v2',
    'rocwmma_i8_i32_signed_finite_u8_hot_residue_v1',
    'rocwmma_i8_i32_signed_finite_u8_mod251_hot_residue_v2',
    'rocwmma_i8_i32_signed_finite_u8_mod255_hot_residue_v2',
    'rocwmma_i8_i32_signed_finite_u8_mod256_hot_residue_v2',
    'rocwmma_i8_i32_signed_mod251_255_256_hot_residue_v2',
    'rocwmma_i8_i32_signed_tiled_mod251_255_256_hot_residue_v2',
    'rocwmma_wrap64_byte_gemm36_candidate_v0',
}
VECTOR_ALU_SELECTED_KERNELS = {
    'hip_vector_alu_i64_exact_192b_v1',
    'hip_vector_alu_i64_gemv_n1_exact_192b_v1',
    'hip_vector_alu_i64_gemv_small_n_exact_192b_v1',
    'hip_vector_alu_u64_exact_192b_v1',
    'hip_vector_alu_u64_gemv_n1_exact_192b_v1',
    'hip_vector_alu_u64_gemv_small_n_exact_192b_v1',
}
CK_SELECTED_KERNELS = {
    'ck_wmma_cshuffle_finite_u8_mod251_centered_epilogue_v2',
    'ck_wmma_cshuffle_finite_u8_mod255_centered_epilogue_v2',
    'ck_wmma_cshuffle_finite_u8_mod256_centered_epilogue_v2',
    'ck_wmma_cshuffle_finite_u8_static_modulus_centered_epilogue_v2',
    'ck_wmma_cshuffle_i8_i32_default_moduli_static_centered_epilogue_v3',
    'ck_wmma_cshuffle_tiled_i8_i32_default_moduli_static_centered_epilogue_v3',
}
ROCWMMA_SELECTED_KERNELS = {
    'rocwmma_i8_i32_signed_finite_u8_hot_residue_v1',
    'rocwmma_i8_i32_signed_finite_u8_mod251_hot_residue_v2',
    'rocwmma_i8_i32_signed_finite_u8_mod255_hot_residue_v2',
    'rocwmma_i8_i32_signed_finite_u8_mod256_hot_residue_v2',
    'rocwmma_i8_i32_signed_mod251_255_256_hot_residue_v2',
    'rocwmma_i8_i32_signed_tiled_mod251_255_256_hot_residue_v2',
}
BOUNDED_I64_EXPORT_KERNELS = {
    'cpu_reference_export_i64',
    'hip_direct_export_i64_device',
    'hip_direct_export_i64_grouped_device',
    'hip_direct_export_i64_tiled_device',
    'vector_alu_output_d2h',
}
BOUNDED_U64_EXPORT_KERNELS = {
    'cpu_reference_export_u64',
    'hip_direct_export_u64_device',
    'hip_direct_export_u64_grouped_device',
    'hip_direct_export_u64_tiled_device',
    'vector_alu_output_d2h',
}
BOUNDED_EXPORT_KERNELS = {
    'cpu_reference_export_i64',
    'cpu_reference_export_u64',
    'hip_direct_export_i64_device',
    'hip_direct_export_i64_grouped_device',
    'hip_direct_export_i64_tiled_device',
    'hip_direct_export_u64_device',
    'hip_direct_export_u64_grouped_device',
    'hip_direct_export_u64_tiled_device',
    'vector_alu_output_d2h',
}
EXACT_WIDE_SIGNED_EXPORT_KERNELS = {
    'cpu_reference_export_exact_wide_signed_limbs',
    'hip_direct_export_exact_wide_signed_fixed_prefix18_fixed_limbs_device',
    'hip_direct_export_exact_wide_signed_fixed_prefix18_variable_limbs_device',
    'hip_direct_export_exact_wide_signed_fixed_prefix20_fixed_limbs_device',
    'hip_direct_export_exact_wide_signed_fixed_prefix20_variable_limbs_device',
    'hip_direct_export_exact_wide_signed_limbs_device',
    'hip_direct_export_exact_wide_signed_tree_crt_limbs_device',
}
EXACT_WIDE_UNSIGNED_EXPORT_KERNELS = {
    'cpu_reference_export_exact_wide_unsigned_limbs',
    'hip_direct_export_exact_wide_unsigned_fixed_prefix18_fixed_limbs_device',
    'hip_direct_export_exact_wide_unsigned_fixed_prefix18_variable_limbs_device',
    'hip_direct_export_exact_wide_unsigned_fixed_prefix20_fixed_limbs_device',
    'hip_direct_export_exact_wide_unsigned_fixed_prefix20_variable_limbs_device',
    'hip_direct_export_exact_wide_unsigned_limbs_device',
    'hip_direct_export_exact_wide_unsigned_tree_crt_limbs_device',
}
EXACT_WIDE_EXPORT_KERNELS = {
    'cpu_reference_export_exact_wide_signed_limbs',
    'cpu_reference_export_exact_wide_unsigned_limbs',
    'hip_direct_export_exact_wide_signed_fixed_prefix18_fixed_limbs_device',
    'hip_direct_export_exact_wide_signed_fixed_prefix18_variable_limbs_device',
    'hip_direct_export_exact_wide_signed_fixed_prefix20_fixed_limbs_device',
    'hip_direct_export_exact_wide_signed_fixed_prefix20_variable_limbs_device',
    'hip_direct_export_exact_wide_signed_limbs_device',
    'hip_direct_export_exact_wide_signed_tree_crt_limbs_device',
    'hip_direct_export_exact_wide_unsigned_fixed_prefix18_fixed_limbs_device',
    'hip_direct_export_exact_wide_unsigned_fixed_prefix18_variable_limbs_device',
    'hip_direct_export_exact_wide_unsigned_fixed_prefix20_fixed_limbs_device',
    'hip_direct_export_exact_wide_unsigned_fixed_prefix20_variable_limbs_device',
    'hip_direct_export_exact_wide_unsigned_limbs_device',
    'hip_direct_export_exact_wide_unsigned_tree_crt_limbs_device',
}
COMPARISON_BASELINE_STATUSES = {
    'missing_reviewed_same_contract_baseline',
    'required_not_recorded',
    'reviewed_release_same_contract_baseline',
    'reviewed_same_contract_baseline',
}
RELEASE_GATE_REVIEW_STATUSES = {
    'not_requested',
    'pending_reviewed_summary',
    'reviewed_blocked',
    'reviewed_passed',
}
SCENARIO_REVIEW_MODES = {
    'release',
    'smoke',
}
PROMOTION_SCOPES = {
    'adaptive_grouped_scheduler_evidence_only',
    'autotune_cache_candidate',
    'baseline_only',
    'comparison_anchor_only',
    'cpu_backed_2048_release_review_candidate',
    'cpu_selector_threshold_evidence_only',
    'execution_path_evidence',
    'explicit_reuse_contract_only',
    'exploratory_only',
    'export_variant_evidence_only',
    'feature_boundary',
    'final_output_chain_evidence_only',
    'final_output_chain_reuse_evidence_only',
    'grouped_dispatch_evidence_only',
    'hip_graph_replay_evidence_only',
    'independent_export_repack_control_only',
    'larger_final_output_chain_evidence_only',
    'layout_comparison_only',
    'layout_metadata_evidence_only',
    'lazy_export_chain_evidence_only',
    'lazy_export_chain_reuse_evidence_only',
    'narrow_margin_review_only',
    'non_promoting_budgeted_dry_run',
    'non_promoting_modulus_map',
    'non_promoting_modulus_set_experiment',
    'not_promotable',
    'proxy_evidence_only',
    'reconstruction_variant_evidence_only',
    'release_gate_review_required',
    'release_review_candidate',
    'resident_lifetime_arena_evidence_only',
    'result_cache_contract_candidate',
    'result_cache_research_only',
    'reuse_contract_evidence_only',
    'scenario_surface_only',
    'streaming_overlap_evidence_only',
    'tile_shape_evidence_only',
    'workload_comparison_only',
}
TARGET_CLAIM_LABELS = {
    'cache_installed',
    'cpu_backed',
    'exploratory',
    'gpu_event_valid',
    'instinct_required',
    'linux_rocm_required',
    'rdna4_required',
    'same_commit',
    'same_contract',
    'windows_gfx1100_local',
}

GROUPED_DISPATCH_STRATEGY_DEVICE_GROUPED_EXACT_WIDE_EXPORT_KERNEL_BATCHED_D2H = 'device_grouped_exact_wide_export_kernel_batched_d2h'
GROUPED_DISPATCH_STRATEGY_DEVICE_GROUPED_PACK_AND_EXACT_WIDE_EXPORT_KERNELS_BATCHED_D2H = 'device_grouped_pack_and_exact_wide_export_kernels_batched_d2h'
GROUPED_DISPATCH_STRATEGY_DEVICE_GROUPED_PACK_GEMM_AND_BOUNDED_EXPORT_KERNELS_BATCHED_D2H = 'device_grouped_pack_gemm_and_bounded_export_kernels_batched_d2h'
GROUPED_DISPATCH_STRATEGY_DEVICE_GROUPED_PACK_GEMM_AND_EXACT_WIDE_EXPORT_KERNELS_BATCHED_D2H = 'device_grouped_pack_gemm_and_exact_wide_export_kernels_batched_d2h'
GROUPED_DISPATCH_STRATEGY_DEVICE_GROUPED_PACK_GEMM_AND_FINITE_EXPORT_KERNEL_BATCHED_D2H = 'device_grouped_pack_gemm_and_finite_export_kernel_batched_d2h'
GROUPED_DISPATCH_STRATEGY_DEVICE_GROUPED_PACK_GEMM_HOST_EXPORTS = 'device_grouped_pack_gemm_host_exports'
GROUPED_DISPATCH_STRATEGY_HOST_PHASE_LOOP_BATCHED_EXACT_WIDE_EXPORT_D2H = 'host_phase_loop_batched_exact_wide_export_d2h'
GROUPED_DISPATCH_STRATEGY_HOST_PHASE_LOOP_PER_TASK_EXPORT = 'host_phase_loop_per_task_export'
GROUPED_DISPATCH_STRATEGY_NOT_REQUESTED = 'not_requested'
