# Generated by tools/metadata_registry.py. Do not edit by hand.
from __future__ import annotations

BENCHMARK_EXECUTION_MODES = {
    'auto_native_to_rns_bridge',
    'benchmark_grouped_dispatch_evidence',
    'benchmark_hip_graph_replay_evidence',
    'benchmark_host_api_batch',
    'benchmark_owned_vector_alu_native_buffers',
    'hip_graph_replay_resident_rns_chain',
    'internal_wrap64_rocwmma_candidate',
    'persistent_resident_matrices',
    'public_oneshot_transient_native_inputs',
    'public_runtime_vector_alu_native_buffers',
    'residue_chain_final_host_export',
    'residue_chain_independent_final_host_export',
    'residue_channel_fusion_native_inputs',
    'residue_current_rns_chain',
    'transient_native_a_resident_b_reuse',
    'transient_native_b_resident_a_reuse',
    'transient_uniform_small_i8_a_resident_i8_b_reuse',
    'transient_uniform_small_i8_ab_inputs',
    'transient_uniform_small_i8_b_resident_i8_a_reuse',
    'vector_native_to_direct_rns_chain',
}
GROUPED_DISPATCH_STATUSES = {
    'executed',
    'metadata_only_unsupported_for_execution_path',
    'not_requested',
}
GROUPED_DISPATCH_EXECUTION_STRATEGIES = {
    'device_grouped_exact_wide_export_kernel_batched_d2h',
    'device_grouped_pack_and_exact_wide_export_kernels_batched_d2h',
    'device_grouped_pack_gemm_and_exact_wide_export_kernels_batched_d2h',
    'device_grouped_pack_gemm_host_exports',
    'host_phase_loop_batched_exact_wide_export_d2h',
    'host_phase_loop_per_task_export',
    'not_requested',
}
GROUPED_DISPATCH_BATCHED_EXACT_WIDE_EXPORT_STRATEGIES = {
    'device_grouped_exact_wide_export_kernel_batched_d2h',
    'device_grouped_pack_and_exact_wide_export_kernels_batched_d2h',
    'device_grouped_pack_gemm_and_exact_wide_export_kernels_batched_d2h',
    'host_phase_loop_batched_exact_wide_export_d2h',
}
GROUPED_TASK_DESCRIPTOR_LAYOUTS = {
    'not_requested',
    'same_shape_resident_task_triplets_v1',
}
GROUPED_TASK_BUCKET_POLICIES = {
    'not_requested',
    'single_same_shape_bucket',
}
GROUPED_TASK_SOURCE_VERSION_POLICIES = {
    'not_requested',
    'per_task_monotonic_source_version_repack',
}
GROUPED_TASK_WORKSPACE_POLICIES = {
    'not_requested',
    'one_workspace_per_task_shared_plan',
}
GROUPED_TASK_CHECKSUM_POLICIES = {
    'combined_per_task_checksum_u64',
    'not_requested',
}
GROUPED_TASK_STATUS_POLICIES = {
    'fail_fast_per_task_operation_status',
    'not_requested',
}
GROUPED_TASK_DEVICE_DESCRIPTOR_POLICIES = {
    'device_pointer_tables_and_compact_slabs',
    'host_resident_task_loop',
    'not_requested',
}
GROUPED_STRATEGY_DEVICE_DESCRIPTOR_POLICIES = {
    'device_grouped_exact_wide_export_kernel_batched_d2h': 'device_pointer_tables_and_compact_slabs',
    'device_grouped_pack_and_exact_wide_export_kernels_batched_d2h': 'device_pointer_tables_and_compact_slabs',
    'device_grouped_pack_gemm_and_exact_wide_export_kernels_batched_d2h': 'device_pointer_tables_and_compact_slabs',
    'device_grouped_pack_gemm_host_exports': 'device_pointer_tables_and_compact_slabs',
    'host_phase_loop_batched_exact_wide_export_d2h': 'host_resident_task_loop',
    'host_phase_loop_per_task_export': 'host_resident_task_loop',
    'not_requested': 'not_requested',
}
OUTPUT_DESTINATION_LAYOUTS = {
    'contiguous_row_major',
    'padded_row_major',
}
STATUS_HANDLING = {
    'not_applicable',
    'required',
    'structurally_elided',
}
OUTPUT_CONTRACT_DOMAINS = {
    'exact_wide_limb_host',
    'finite_u8_host',
    'native_i64_u64_host',
    'rns_residue_current',
    'wrap64_u64_host',
}
DIRECT_HIP_EXPORT_STAGING_POLICIES = {
    'disabled_by_RNS8_HIP_PINNED_EXPORT_STAGING',
    'exact_wide_signed_forced_only_local_gfx1100_padded_staging_loses',
    'forced_for_large_outputs_by_RNS8_HIP_PINNED_EXPORT_STAGING',
    'large_padded_outputs_only_default',
    'not_applicable',
    'wrap64_forced_only_pending_padded_staging_evidence',
}

GROUPED_DISPATCH_STRATEGY_DEVICE_GROUPED_EXACT_WIDE_EXPORT_KERNEL_BATCHED_D2H = 'device_grouped_exact_wide_export_kernel_batched_d2h'
GROUPED_DISPATCH_STRATEGY_DEVICE_GROUPED_PACK_AND_EXACT_WIDE_EXPORT_KERNELS_BATCHED_D2H = 'device_grouped_pack_and_exact_wide_export_kernels_batched_d2h'
GROUPED_DISPATCH_STRATEGY_DEVICE_GROUPED_PACK_GEMM_AND_EXACT_WIDE_EXPORT_KERNELS_BATCHED_D2H = 'device_grouped_pack_gemm_and_exact_wide_export_kernels_batched_d2h'
GROUPED_DISPATCH_STRATEGY_DEVICE_GROUPED_PACK_GEMM_HOST_EXPORTS = 'device_grouped_pack_gemm_host_exports'
GROUPED_DISPATCH_STRATEGY_HOST_PHASE_LOOP_BATCHED_EXACT_WIDE_EXPORT_D2H = 'host_phase_loop_batched_exact_wide_export_d2h'
GROUPED_DISPATCH_STRATEGY_HOST_PHASE_LOOP_PER_TASK_EXPORT = 'host_phase_loop_per_task_export'
GROUPED_DISPATCH_STRATEGY_NOT_REQUESTED = 'not_requested'
