set(RNS8_INSTALL_CONFIG_DIR "${CMAKE_INSTALL_LIBDIR}/cmake/RNS8")
set(RNS8_INSTALL_TARGETS rns8_static)
if(RNS8_BUILD_SHARED)
  list(PREPEND RNS8_INSTALL_TARGETS rns8)
endif()

install(
  TARGETS ${RNS8_INSTALL_TARGETS}
  EXPORT RNS8Targets
  RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}" COMPONENT Runtime
  LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}" COMPONENT Runtime
  ARCHIVE DESTINATION "${CMAKE_INSTALL_LIBDIR}" COMPONENT Development
)

install(
  DIRECTORY include/rns8
  DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}"
  COMPONENT Development
)

install(
  EXPORT RNS8Targets
  FILE RNS8Targets.cmake
  NAMESPACE rns8::
  DESTINATION "${RNS8_INSTALL_CONFIG_DIR}"
  COMPONENT Development
)

configure_package_config_file(
  cmake/RNS8Config.cmake.in
  "${CMAKE_CURRENT_BINARY_DIR}/RNS8Config.cmake"
  INSTALL_DESTINATION "${RNS8_INSTALL_CONFIG_DIR}"
)

write_basic_package_version_file(
  "${CMAKE_CURRENT_BINARY_DIR}/RNS8ConfigVersion.cmake"
  VERSION "${PROJECT_VERSION}"
  COMPATIBILITY SameMajorVersion
)

install(
  FILES
    "${CMAKE_CURRENT_BINARY_DIR}/RNS8Config.cmake"
    "${CMAKE_CURRENT_BINARY_DIR}/RNS8ConfigVersion.cmake"
  DESTINATION "${RNS8_INSTALL_CONFIG_DIR}"
  COMPONENT Development
)
